// datasources.js — the public datasets & methods that image the Earth's
// interior. Curated starting point (the in-app "How we know" panel); the
// radial PREM model used here and these are how the field actually knows.
export const DATA_GROUPS = [
  { cat:'1-D reference models (the baseline)', items:[
    {name:'PREM', m:'radial Vp, Vs, density, attenuation', d:'whole Earth', u:'https://ds.iris.edu/spud/earthmodel', one:'The standard average Earth — every depth value in this app comes from it.'},
    {name:'AK135 / IASP91', m:'radial velocity (travel-time)', d:'whole Earth', u:'http://rses.anu.edu.au/seismology/ak135/ak135f.html', one:'Travel-time models used to locate earthquakes and time seismic phases.'},
    {name:'STW105 / REM', m:'radial v, density, anisotropy', d:'whole Earth', u:'https://ds.iris.edu/ds/products/emc/', one:'Reference models tuned to also fit the free-oscillation data.'},
  ]},
  { cat:'Global mantle tomography (the “scan”)', items:[
    {name:'S40RTS / S20RTS', m:'shear-velocity anomaly ΔVs', d:'whole mantle', u:'https://www.earth.lsa.umich.edu/~jritsema/research.html', one:'A classic ΔVs model — the LLSVPs and slabs you see come from models like this.'},
    {name:'SEMUCB-WM1', m:'ΔVs, radial anisotropy (full-waveform)', d:'whole mantle', u:'https://ds.iris.edu/ds/products/emc/', one:'Full-waveform model; sharply images the two deep hot piles and plume roots.'},
    {name:'GyPSuM', m:'ΔVs & ΔVp + density', d:'whole mantle', u:'https://ds.iris.edu/ds/products/emc-gypsum/', one:'Joint model tying seismic speeds to density and mantle flow.'},
    {name:'S362ANI+M / SAVANI / SP12RTS / SEISGLOB2', m:'ΔVs (±Vp, anisotropy)', d:'whole mantle', u:'https://ds.iris.edu/ds/products/emc/', one:'The family of public global models — they broadly agree on the big structures.'},
    {name:'LLNL-G3Dv3 / UU-P07 / GAP-P4 (P-wave)', m:'ΔVp', d:'whole mantle', u:'https://ds.iris.edu/ds/products/emc/', one:'P-wave models that resolve cold subducted slabs especially well.'},
  ]},
  { cat:'Seismic methods beyond tomography', items:[
    {name:'Free oscillations / normal modes', m:'density + radial structure', d:'whole Earth', u:'https://ds.iris.edu/ds/nodes/dmc/', one:'The whole planet rings for days after big quakes — the tones fix its density.'},
    {name:'Receiver functions & SS/PP precursors', m:'410 & 660 km discontinuity depth', d:'transition zone', u:'https://ds.iris.edu/ds/products/', one:'Reflections off mineral phase changes map the depth of the 410 & 660.'},
    {name:'SKS/SKKS splitting', m:'mantle anisotropy → flow direction', d:'upper mantle, D″', u:'https://ds.iris.edu/ds/products/sws-dbs/', one:'Split shear waves reveal which way the mantle is flowing.'},
    {name:'PKP / PKiKP / ScS', m:'core structure, ULVZs, inner core', d:'D″ → inner core', u:'https://ds.iris.edu/ds/nodes/dmc/', one:'Waves that graze or cross the core probe its boundary and the inner core.'},
    {name:'CRUST1.0 / LITHO1.0', m:'crust & lithosphere thickness', d:'crust + lithosphere', u:'https://igppweb.ucsd.edu/~gabi/crust1.html', one:'Global maps of how thick the crust and rigid plate are.'},
  ]},
  { cat:'The core & the magnetic field', items:[
    {name:'IGRF-14 / CHAOS-7 / gufm1', m:'geomagnetic field & its drift', d:'outer core', u:'https://www.ncei.noaa.gov/products/international-geomagnetic-reference-field', one:'The field generated by churning liquid iron — its changes track core flow.'},
    {name:'Swarm / INTERMAGNET / NCEI', m:'field measurements (satellite + ground)', d:'outer core', u:'https://intermagnet.org/', one:'The raw magnetic observations the core-field models are built from.'},
    {name:'Inner-core anisotropy & rotation', m:'inner-core fabric & spin', d:'inner core', u:'https://ds.iris.edu/ds/nodes/dmc/', one:'PKP waves travel faster along the spin axis — and the inner core may rotate slightly differently.'},
  ]},
  { cat:'Gravity & geodesy', items:[
    {name:'GRACE / GRACE-FO', m:'time-varying gravity → mass flow', d:'whole Earth', u:'https://podaac.jpl.nasa.gov/GRACE', one:'Twin satellites weigh the planet month to month — water, ice, deep mass.'},
    {name:'GOCE / EGM2008 / ICGEM', m:'static gravity field & geoid', d:'whole mantle', u:'https://icgem.gfz-potsdam.de/', one:'The lumpy gravity field reflects dense slabs and buoyant hot piles at depth.'},
  ]},
  { cat:'Particles, heat & rocks', items:[
    {name:'Geoneutrinos — KamLAND & Borexino', m:'radiogenic heat, mantle U/Th', d:'whole Earth', u:'https://kamland.stanford.edu/', one:'Ghostly particles from uranium/thorium decay tell us how much the Earth heats itself.'},
    {name:'Global Heat Flow Database (NGHF)', m:'surface heat flux', d:'whole Earth', u:'https://ihfc-iugg.org/products/global-heat-flow-database', one:'How fast heat escapes — the budget for all this convection.'},
    {name:'Magnetotellurics (USArray MT)', m:'electrical conductivity → melt/water', d:'crust → upper mantle', u:'https://ds.iris.edu/ds/products/emtf/', one:'Natural currents reveal where the mantle is wet or partly molten.'},
    {name:'Mineral physics (diamond-anvil / ab-initio)', m:'phase, density, melting at depth', d:'whole Earth', u:'https://www.earthref.org/', one:'Lab experiments at core pressures tell us what the seismic speeds are made of.'},
  ]},
  { cat:'Slabs, plates & portals', items:[
    {name:'Slab2 (USGS)', m:'geometry of every subducting slab', d:'upper mantle', u:'https://www.sciencebase.gov/catalog/item/5aa1b00ee4b0b1c392e86467', one:'A 3-D model of where today’s ocean floor is diving down.'},
    {name:'Atlas of the Underworld', m:'identified subducted slabs', d:'whole mantle', u:'http://www.atlas-of-the-underworld.org/', one:'A catalogue tying blue blobs in the deep mantle to ancient lost oceans.'},
    {name:'IRIS / EarthScope EMC + SubMachine', m:'download & compare tomography', d:'whole Earth', u:'http://submachine.earth.ox.ac.uk/', one:'Where the models live and can be sliced — the best place to explore the real data.'},
    {name:'FDSN / ObsPy / GPlates', m:'raw waveforms & plate reconstructions', d:'whole Earth', u:'https://www.fdsn.org/', one:'Open seismic archives and plate-motion software anyone can use.'},
  ]},
];

export function dataSourcesHTML(groups){
  return groups.map(g=>`<div class="data-cat">${g.cat}</div>`+
    g.items.map(it=>`<div class="data-item"><b>${it.name}</b>`+
      `<div class="di-meta">${it.m} · ${it.d}</div>`+
      `<div class="di-one">${it.one}</div>`+
      (it.u?`<a href="${it.u}" target="_blank" rel="noopener">${it.u.replace(/^https?:\/\//,'').split('/')[0]} ↗</a>`:'')+
    `</div>`).join('')
  ).join('');
}
